### ISSUE TITLE
key missing

### ISSUE THREAD

**Issue by ebridge2** [bids-apps/base_fsl#2]
Line from dockerfile:

```
apt-key adv --recv-keys --keyserver hkp://pgp.mit.edu:80 0xA5D32F012649A5A9
```

Error in build:
```
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.XGxZgmuB72 --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/jonathonf-python-2_7.gpg --recv-keys --keyserver hkp://pgp.mit.edu:80 0xA5D32F012649A5A9
gpg: requesting key 2649A5A9 from hkp server pgp.mit.edu
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error
```

@chrisfilo error when tying together bids dockerfiles; seems like this key has been removed or something from pgp.mit.edu. thoughts on a fix?

**Comment by chrisgorgo** [comment]
It's a server time out not a missing key issue. It happens sometimes. @neurodebian folks have some workarounds making it more robust in their Dockerfiles. You can look them up and maybe send a PR to this repo? Thanks in advance.

**Comment by ebridge2** [comment]
```
http://pgp.mit.edu/pks/lookup?search=0xA5D32F012649A5A9&op=index
```

from pgp.mit.edu manual search; looks like their servers are down or something so i guess that makes sense :) thanks!

**Comment by LittleVulpix** [comment]
I realize this may be a bit of a necro but I came across this issue as well.

Solution was to use another of the gpg servers, as outlined here:

https://superuser.com/questions/1250681/why-am-i-unable-to-fetch-pgp-keys-from-commandline?rq=1

I used hkp://p80.pool.sks-keyservers.net:80 which worked like a charm.
